language: cpp
compiler:
  - g++
before_install:
  - chmod +x build_log2bgp
script: $PWD/build_log2bgp
branches:
  only:
    - master
notifications:
  recipients:
    - all@log2.co
  email:
    on_success: change
    on_failure: always 