language: cpp
compiler:
  - g++
before_script:
  - sudo apt-get install libreadline-dev
  - cd bigplgd
script: make
branches:
  only:
    - master
notifications:
  recipients:
    - aaron.hebert@gmail.com
    - aaron.hebert@rackspace.com
  email:
    on_success: change
    on_failure: always