language: cpp
compiler:
  - g++
  - clang++
before_install:
  - rvm use $RVM --install --binary --fuzzy
  - gem update --system
  - gem --version
before_script:
  - travis_retry bundle
  - travis_retry ./configure
script: rake
branches:
  only:
    - master
notifications:
  recipients:
    - aaron.hebert@gmail.com
    - aaron.hebert@rackspace.com
  email:
    on_success: change
    on_failure: always