language: cpp
compiler:
  - g++
before_install:
  - chmod +x build_bigplg
script: $PWD/build_bigplg
branches:
  only:
    - master
notifications:
  recipients:
    - aaron.hebert@gmail.com
    - evanscottgray@gmail.com
    - omarfahmikhalid@gmail.com
  email:
    on_success: change
    on_failure: always 