#!/bin/bash
echo "preping deps..."
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y > /dev/null
sudo apt-get update -qq
sudo apt-get install -qq libreadline-dev  > /dev/null
sudo apt-get install -qq g++-4.8  > /dev/null
sudo apt-get install -qq ruby  > /dev/null
gem install sinatra  > /dev/null
cd bigplgd
echo "make, yeah bitch!..."
make