#!/bin/bash
echo "building |"
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
sudo apt-get update -qq
sudo apt-get install -qq libreadline-dev gcc-4.8
export CXX="g++-4.8" CC="gcc-4.8"
cd bigplgd
make